options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 0
  class-name-format:
    - 0
    - convention: hyphenatedlowercase
  empty-line-between-blocks: 0
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-notation: 0
  id-name-format:
    - 0
    - convention: hyphenatedlowercase
  indentation:
    - 2
    - size: 2
  leading-zero:
    - 2
    - include: false
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations: 0
  nesting-depth:
    - 0
    - max-depth: 3
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-ids: 0
  no-important: 0
  no-mergeable-selectors: 2
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []
  placeholder-in-extend: 0
  placeholder-name-format:
    - 0
    - convention: hyphenatedlowercase
  property-sort-order:
    - 0
    - ignore-custom-properties: false
      order:
        - display
        - visibility
        - float
        - clear
        - position
        - top
        - right
        - bottom
        - left
        - z-index
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - overflow
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - border
        - border-top
        - border-right
        - border-bottom
        - border-left
        - border-width
        - border-top-width
        - border-right-width
        - border-bottom-width
        - border-left-width
        - border-style
        - border-top-style
        - border-right-style
        - border-bottom-style
        - border-left-style
        - border-color
        - border-top-color
        - border-right-color
        - border-bottom-color
        - border-left-color
        - outline
        - list-style
        - table-layout
        - caption-side
        - border-collapse
        - border-spacing
        - empty-cells
        - font
        - font-family
        - font-size
        - line-height
        - font-weight
        - text-align
        - text-indent
        - text-transform
        - text-decoration
        - letter-spacing
        - word-spacing
        - white-space
        - vertical-align
        - color
        - background
        - background-color
        - background-image
        - background-repeat
        - background-position
        - opacity
        - cursor
        - content
        - quotes
  quotes:
    - 2
    - style: single
  shorthand-values:
    - 2
    - allowed-shorthands:
      - 1
  space-after-colon:
    - 2
    - include: true
  space-before-brace:
    - 2
    - include: true
  trailing-semicolon: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit: 2
